- name: Install curl
  ansible.builtin.package:
    name: curl
    state: latest
    when: ansible_facts['distribution'] != 'Rocky' or ansible_facts['distribution'] != 'RedHat'

- name: Install git
  ansible.builtin.package:
    name: git
    state: latest

- name: Install net-tools
  ansible.builtin.package:
    name: net-tools
    state: latest
