---
- name: Cleanup old install
  ansible.builtin.command: "for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do sudo apt-get remove $pkg; done"
  ignore_errors: true

- name: Install prerequisites
  ansible.builtin.package:
    pkg:
      - ca-certificates
      - curl
    state: latest

- name: Install keyring
  ansible.builtin.command: "install -m 0755 -d /etc/apt/keyrings"

- name: Download the docker package
  ansible.builtin.uri:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0755"
  register: docker_gpg_result
  ignore_errors: true

- name: Check if the download was successful
  ansible.builtin.fail:
    msg: "Failed to download the docker gpg key"
  when: docker_gpg_result.failed and docker_gpg_result.status != 304

- name: Changing permissions
  ansible.builtin.file:
    path: "/etc/apt/keyrings/docker.asc"
    mode: "a+r"

- name: Add the docker repository
  ansible.builtin.shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update Apt with the docker registry
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 0 # force the update

- name: Install docker packages
  ansible.builtin.package:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Test installation
  ansible.builtin.command: "docker -v"
  register: docker_version

- debug:
    msg: "{{ docker_version.stdout }}"
  failed_when: docker_version.rc != 0
  notify: Start dockerd
