# Install Docker on different Linux distributions
# -------------------------------------------
---
- name: Get distro
  ansible.builtin.debug:
    var: ansible_facts['distribution']

- name: Install Docker on Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install Docker on Debian
  include_tasks: debian.yml
  when: ansible_facts['distribution'] == 'Debian'

- name: Install Docker on Rocky
  include_tasks: rocky.yml
  when: ansible_facts['distribution'] == 'Rocky' or ansible_facts['distribution'] == 'RedHat'

- name: Start Docker Deamon
  include_tasks: service.yml
