---
- name: Restart ssh service - server
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: not install_on_docker

- name: Restart ssh service - docker
  become: true
  ansible.builtin.shell: service ssh restart
  when: install_on_docker
