---
- name: Start dockerd
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes
  # Failed on docker image - To disable in production
  ignore_errors: "{{ install_on_docker }}"
