---
- name: Start docker daemon
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  ignore_errors: "{{ install_on_docker | default(false) }}"

- name: Stop docker daemon
  ansible.builtin.systemd:
    name: docker
    state: stopped
  ignore_errors: "{{ install_on_docker | default(false) }}"
