# TODO: rework !
---
- name: Check if ssh_private_key is defined
  ansible.builtin.fail:
    msg: "ssh_private_key is not defined"
  when: ssh_private_key is not defined

- name: Check if ssh_public_key is defined
  ansible.builtin.fail:
    msg: "ssh_public_key is not defined"
  when: ssh_public_key is not defined

- name: Check if private_key_filename is defined
  ansible.builtin.fail:
    msg: "private_key_filename is not defined"
  when: private_key_filename is not defined

- name: Check if public_key_filename is defined
  ansible.builtin.fail:
    msg: "public_key_filename is not defined"
  when: public_key_filename is not defined

- name: Ensure ssh folder exists
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: "0700"

- name: Copy private key
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: "~/.ssh/{{ private_key_filename }}"
    mode: "0600"
  when: ssh_key_filename_identifier is not defined

- name: Copy public key
  ansible.builtin.copy:
    content: "{{ ssh_public_key }}"
    dest: "~/.ssh/{{ public_key_filename }}"
    mode: "0644"
  when: ssh_key_filename_identifier is not defined

- name: Copy private key
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: "~/.ssh/{{ private_key_filename }}_{{ ssh_key_filename_identifier }}"
    mode: "0600"
  when: ssh_key_filename_identifier is defined

- name: Copy public key
  ansible.builtin.copy:
    content: "{{ ssh_public_key }}"
    dest: "~/.ssh/{{ public_key_filename }}_{{ ssh_key_filename_identifier }}"
    mode: "0644"
  when: ssh_key_filename_identifier is defined

# ADD SSH KEY TO AGENT

- name: Start SSH agent
  ansible.builtin.shell: |
    eval $(ssh-agent)

- name: Add SSH key
  ansible.builtin.shell: |
    ssh-add ~/.ssh/{{ private_key_filename }}{{ ssh_key_suffix }}

- name: Check if the SSH key has been correctly added
  ansible.builtin.shell: |
    ssh-add -l
  register: ssh_key_check

- name: Debug SSH key check
  ansible.builtin.debug:
    var: ssh_key_check.stdout
